apiVersion: v1
kind: Service
metadata:
  name: send-kafka-service
spec:
  selector:
    app: send-kafka
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-kafka
spec:
  selector:
    matchLabels:
      app: send-kafka
  replicas: 4
  template:
    metadata:
      labels:
        app: send-kafka
    spec:
      containers:
      - name: send-kafka
        image: send-kafka:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000