apiVersion: v1
kind: Pod
metadata:
  name: producer-kafka
  labels:
    name: producer-kafka
spec:
  containers:
    - name: producer-kafka
      image: ddotu2612/producer-kafka:2.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: "KAFKA_BOOTSTRAP_SERVER"
          value: "kafka.default.svc.cluster.local:9092"
      ports:
        - containerPort: 5000
