apiVersion: v1
kind: Service
metadata:
 labels:
 k8s-app: producer-kafka
 name: producer-kafka
 namespace: producer-kafka
spec:
 type: NodePort
 ports:
 — port: 4025
 selector:
 k8s-app: producer-kafka